
############### Paramètres du multilingue ###############
[fr]
  # français d’abord
  weight = 1
  title = "Navigations anthologiques"
  [fr.params]
    description = "Site web des Navigations anthologiques (journées d'étude) se déroulant à l'Université de Montréal du 27 octobre au 29 octobre 2022, organisées par la CRCEN."
  copyright = "Thème conçu par [Themefisher](https://themefisher.com/), développé par [Gethugothemes](https://gethugothemes.com/) et adapté par la [CRCÉN](https://ecrituresnumeriques.ca)"
[en]
  title = "Anthological Navigations"
  [en.params]
    description = "Website of the Workshop Anthological Navigations, organized by CRCDT and held at the University of Montreal from the 27th to 29th of October 2022."
  weight = 2
  copyright = "Theme designed by [Themefisher](https://themefisher.com/), developed by [Gethugothemes](https://gethugothemes.com/) and adapted by [CRCDT](https://ecrituresnumeriques.ca/en)"
