
############### Paramètres du multilingue ###############
[fr]
  # français d’abord
  weight = 1
  title = "Colloque"
  description = ""
[en]
  title = "Colloquium"
  description = ""
  weight = 2

[it]
  weight = 3
