
############### Paramètres du multilingue ###############
[fr]
  # français d’abord
  weight = 1
  title = "Navigations anthologiques"
  description = "Site web des Navigations anthologiques (journées d'étude) se déroulant à l'Université de Montréal du 27 octobre au 29 octobre 2022, organisées par la CRCEN."
[en]
  title = "Anthological Navigations"
  description = "Website of the Workshop Anthological Navigations, organized by CRCDT and held at the University of Montreal from the 27th to 29th of October 2022."
  weight = 2
