####################### navigation ##########################

# main menu
[[main]]
weight = 1
name = "Schedule"
url = "schedule"

[[main]]
weight = 2
name = "Hackathon"
url = "hackathon"

[[main]]
weight = 3
name = "Archives"
url = "archives"

[[main]]
name = "Contact"
url = "contact"
weight = 4
